# Alle containere i projektet
services:

  # MySQL database
  mysql:
    # Brug officiel MySQL 8
    image: mysql:8.0
    # Giv containeren et tydeligt navn
    container_name: adventurexp-mysql
    # Genstart automatisk ved crash
    restart: unless-stopped

    # Initielle credentials og DB-navn
    environment:
      # Root-adgang (kun lokalt)
      MYSQL_ROOT_PASSWORD: rootpassword
      # Opret denne database ved start
      MYSQL_DATABASE: adventurexp
      # App-bruger (ikke-root)
      MYSQL_USER: appuser
      # App-brugerens password
      MYSQL_PASSWORD: apppassword

    # Vedvarende lagring og custom config
    volumes:
      # Gem DB-data uden for containeren
      - mysql_data:/var/lib/mysql
      # Indlæs egen MySQL-konfiguration (read-only)
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro

    # Begræns RAM-forbrug
    mem_limit: 1g

    # Internt netværk mellem services
    networks:
      - adventurexp-net

    # Vent til databasen svarer før andre services starter
    healthcheck:
      # Ping MySQL som readiness-tjek
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-prootpassword"]
      # Kør tjek hvert 5. sekund
      interval: 5s
      # Maks ventetid pr. tjek
      timeout: 3s
      # Antal forsøg før "unhealthy"
      retries: 30
      # Ekstra tid efter kold start
      start_period: 20s

  # Spring Boot applikation
  app:
    # Byg image fra Dockerfile i projektroden
    build: .
    # Navn på app-containeren
    container_name: adventurexp-app
    # Genstart automatisk ved crash
    restart: unless-stopped

    # Eksponér HTTP-port til host
    ports:
      # Host 8080 -> Container 8080
      - "8080:8080"

    # Spring-konfiguration via env vars
    environment:
      # Brug docker-profilen
      SPRING_PROFILES_ACTIVE: docker
      # JDBC URL (host = service-navnet "mysql")
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/adventurexp?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      # DB-bruger til app
      SPRING_DATASOURCE_USERNAME: appuser
      # DB-password til app
      SPRING_DATASOURCE_PASSWORD: apppassword
      # Skema håndteres af Flyway (ikke auto-create)
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      # Kør Flyway ved opstart
      SPRING_FLYWAY_ENABLED: "true"
      # Placering af migrations i jar
      SPRING_FLYWAY_LOCATIONS: classpath:db/migration

    # Start først når MySQL er klar
    depends_on:
      mysql:
        # Vent på healthcheck=healthy
        condition: service_healthy

    # Begræns RAM-forbrug for app
    mem_limit: 512m

    # Samme interne netværk som DB
    networks:
      - adventurexp-net

# Definér navngivet volumen til MySQL-data
volumes:
  # Vedvarende lager til databasefiler
  mysql_data:

# Definér privat bridge-netværk
networks:
  # Isoleret net mellem app og DB
  adventurexp-net:
    # Standard bridge-driver
    driver: bridge
